// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > src/types/database.ts
// Do NOT manually edit this file after generation.

export type Database = Record<string, never>;
